#!/usr/bin/env php
<?php
// Старое имя точки входа сохранено как подсказка, команды перенесены в Artisan.
fwrite(STDOUT, "Управление: php artisan hspm:admin <логин>\nИмпорт: php artisan hspm:import <тип> <файл>\nМиграции: php artisan migrate\n");
